on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "*"
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: xvfb-run -a yarn test
        if: runner.os == 'Linux'
      - id: check
        if: success()
        uses: EndBug/version-check@v1
        with:
          diff-search: true
      - if: steps.check.outputs.changed == 'true'
        run: yarn run publish --pre-release
